### ISSUE TITLE
Hibernate is not working

### ISSUE THREAD

**Issue by obbcth** [obbcth/Notebook9-Metal-Hackintosh#1]
Note: you should remove battery physically to wake up.

Plus, I need to test if I can wake up by unpluging usb type-c devices.

**Comment by obbcth** [comment]
I heard that removing _PRW in DSDT can solve this problem. I will try it. [#Link](https://x86.co.kr/index.php?mid=mymac&category=1162962&document_srl=5355499)

**Comment by PeterSuh-Q3** [comment]
그리고 저도 위에 언급하신 DSDT 에서 _PRW를 제거하는 스크립트를 받아 패치적용하였으나, 잠자기후 전원종료 불가현상은 동일하게 지속되었습니다.

**Comment by obbcth** [comment]
제 개인적인 생각으로는, 아마 삼성 바이오스 단에서 무슨 문제가 있지 않나 생각합니다.
노트북9 메탈을 비롯한 다른 삼성 노트북들도 예전에 해킨해서 써봤는데, 잠자기는 전혀 해결될 가망이 안보이네요.

HibernationFixup.kext 파일이 전원종료 후 부팅불가 상태로 빠지지 않는다면, EFI 폴더에 추가해도 괜찮을 것 같네요.
혹시 kext 파일 외 boot-arg 등 따로 추가해야 할 부분이 있나요?

ps, 저는 지금 이 기기를 가지고 있지 않아서.. 확인은 못 할 거 같습니다. 잘 작동된다면 Pull Request 넣어주시면 이 레포지토리에 Merge 해놓겠습니다.

**Comment by PeterSuh-Q3** [comment]
1.5 릴리즈로 생성해 주셔서 감사합니다. 그런데, 리소스 디렉토리가 누락된것 같습니다.
포크된 제 레파지토리엔 최종 리소스 디렉토리까지 업로드 완료 했습니다.
한번만 더 최종버전 업데이트 부탁드리겠습니다.

**Comment by obbcth** [comment]
앗 Resources 폴더를 제가 빼먹었네요.
#8 은 제 레포지토리랑 구조가 달라 Merge가 안되네요. 이건 제가 따로 업로드하겠습니다.
감사합니다.

**Comment by obbcth** [comment]
fixed #14
