### ISSUE TITLE
잠자기 이후 못깨어나는 문제 해결되었습니다.

### ISSUE THREAD

**Issue by PeterSuh-Q3** [obbcth/Notebook9-Metal-Hackintosh#14]
3년전인 2021년에 x86에 회원님이 이미 공유를 해주셨었는데, 이제야 해결을 봤습니다.

https://x86.co.kr/info/6381551

DSDT.aml 은 일단 비활성화 해야 하고
이분이 공유주신 SSDT-Wake-Fix.aml 을 추가하기만 하면 됩니다.

Fork 한 제 Repo 는 버전 1.7로 오늘 릴리즈 했습니다.
참고해 보시기 바랍니다.

https://github.com/PeterSuh-Q3/Notebook9-Metal-Hackintosh-BigSur11.4

이제 잠자기가 제대로 동작되서 너무 기쁩니다.^^

**Comment by obbcth** [comment]
잊고있다가 최근에 들어와보니 수많은 변경점들이 있었네요. PR 반영했습니다. 감사합니다😁
